# Generated by Django 4.2.1 on 2023-06-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.infrastructure'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.employe'),
        ),
    ]
